version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=prisma
    - POSTGRES_PASSWORD=prisma
    - POSTGRES_DB=users
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
  server:
    build: .
    depends_on:
      - postgres
    ports:
    - 8005:8005
    volumes:
    - ./:/app
    command: npm start

