version: '3.8'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: datasprints
        port: 4466
        databases:
          users:
            connector: postgres
            host: postgres
            port: 5432
            user: pedro
            password: password
            connectionLimit: 5
  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build:
      context: .
    depends_on:
      - prisma
      - db
    ports:
    - 8005:8005
    environment:
    - SERVER_PORT=8005
    volumes:
    - ./:/app
    command: npm run start
volumes:
  postgres: ~
