version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=prisma
    - POSTGRES_PASSWORD=prisma
    -  POSTGRES_DB=users
    volumes:
      - /var/lib/postgresql/data
    ports:
    - 5432:5432
  server:
    build: .
    depends_on:
      - db
    ports:
    - "8005:8005"
    environment:
    - DATABASE_URL=postgresql://prisma:prisma@db:5432/users
    command: npm start
volumes:
  postgres:

